Hw3_Task1
DenisKrivoruchko11/SPBUHomework pull request #11
Opened 2020-07-29 16:00 UTC by DenisKrivoruchko11

Added a solution and tests for Homework3 Task1

2020-11-28 18:26 UTC, SpirinEgor requested changes

2020-11-28 18:26 UTC, SpirinEgor commented on src/main/kotlin/homeworks/homework3/task1/AvlTree.kt
> +private fun <K : Comparable<K>, T> getValueByKey(key: K, item: AvlTreeItem<K, T>?): T? {
А почему эти функции не внутри класса?
У тебя есть конкретный класс, который должен спрятать логику работы с вершинами внутри. А у тебя как-то получается, что метод класса ниже просто вызывает эти функции.

2020-11-28 18:26 UTC, SpirinEgor commented on src/main/kotlin/homeworks/homework3/task1/AvlTree.kt
> +private fun <K : Comparable<K>, T> getValueByKey(key: K, item: AvlTreeItem<K, T>?): T? {
Если говорить более формально, то тут инкапсуляция нарушается

2020-11-29 15:29 UTC, DenisKrivoruchko11 commented on src/main/kotlin/homeworks/homework3/task1/AvlTree.kt
> +private fun <K : Comparable<K>, T> getValueByKey(key: K, item: AvlTreeItem<K, T>?): T? {
исправил

2020-11-30 12:41 UTC, SpirinEgor approved these changes

2020-11-30 12:41 UTC, merged