Hw4_Task1
DenisKrivoruchko11/SPBUHomework pull request #12
Opened 2020-08-05 08:45 UTC by DenisKrivoruchko11

Add a solution and tests for hw4 task1

2020-11-28 18:31 UTC, SpirinEgor requested changes

2020-11-28 18:31 UTC, SpirinEgor commented on src/main/kotlin/homeworks/homework4/task1/HashFunctions.kt
> +        HashKeys.Hash3 -> fun(value: String): Int {
Эмм, я правильно понял, что у тебя тут 5 абсолютно одинаковых функций. Которые отличаются в одном месте константной?
Не, это совсем фигня. Должна быть какая-то параметризованная функция хотя бы.

2020-11-28 18:31 UTC, SpirinEgor commented on src/main/kotlin/homeworks/homework4/task1/HashTable.kt
> +private fun getSize(table: HashTable): Int {
Опять же, почему функции, а тем более геттеры, вынесены наружу.

2020-11-28 18:31 UTC, SpirinEgor commented on src/main/kotlin/homeworks/homework4/task1/enums/HashKeys.kt
> +}
Вот этого не понял. Зачем это отдельно? Укажи в enum и всё

2020-11-30 12:52 UTC, DenisKrivoruchko11 commented on src/main/kotlin/homeworks/homework4/task1/enums/HashKeys.kt
> +}
исправлено

2020-11-30 12:52 UTC, DenisKrivoruchko11 commented on src/main/kotlin/homeworks/homework4/task1/HashTable.kt
> +private fun getSize(table: HashTable): Int {
исправлено

2020-11-30 12:52 UTC, DenisKrivoruchko11 commented on src/main/kotlin/homeworks/homework4/task1/HashFunctions.kt
> +        HashKeys.Hash3 -> fun(value: String): Int {
исправлено

2020-11-30 12:53 UTC, SpirinEgor approved these changes

2020-11-30 12:54 UTC, merged