Hw4_Task2
DenisKrivoruchko11/SPBUHomework pull request #13
Opened 2020-08-13 08:51 UTC by DenisKrivoruchko11

Added solution and tests for hw4 task2

2020-11-28 18:47 UTC, SpirinEgor requested changes

2020-11-28 18:47 UTC, SpirinEgor commented on src/main/kotlin/homeworks/homework4/task2/Tree.kt
> +private fun fillTree(input: List<String>): TreeItem {
Эта функция точно часть класса. Она знает про устройство дерева.

2020-11-29 19:18 UTC, DenisKrivoruchko11 commented on src/main/kotlin/homeworks/homework4/task2/Tree.kt
> +private fun fillTree(input: List<String>): TreeItem {
исправлено

2020-11-30 12:42 UTC, SpirinEgor approved these changes

2020-11-30 12:42 UTC, merged