Hw1_Task5
DenisKrivoruchko11/SPBUHomework pull request #6
Opened 2020-05-13 21:27 UTC by DenisKrivoruchko11

2020-05-20 15:20 UTC, SpirinEgor requested changes

2020-05-20 15:20 UTC, SpirinEgor commented on src/main/kotlin/homeworks/homework1/task5/Task5.kt
> +    val listOfFileStrings = File(filePath).useLines { it.toList() }
А что произойдёт, если такого файла не существует?

2020-05-20 15:20 UTC, SpirinEgor commented on src/main/kotlin/homeworks/homework1/task5/Task5.kt
> +    }
Для подобного есть `count`

2020-05-20 15:20 UTC, SpirinEgor commented on src/main/kotlin/homeworks/homework1/task5/Task5.kt
> +    val scan = Scanner(System.`in`)
Для чего тут `Scanner`? Обычный `readline()` намного лучше

2020-06-02 10:57 UTC, DenisKrivoruchko11 commented on src/main/kotlin/homeworks/homework1/task5/Task5.kt
> +    val listOfFileStrings = File(filePath).useLines { it.toList() }
Создастся новый

2020-06-02 12:27 UTC, SpirinEgor requested changes

2020-06-02 12:27 UTC, SpirinEgor commented on src/main/kotlin/homeworks/homework1/task5/Task5.kt
> +    val listOfFileStrings = File(filePath).useLines { it.toList() }
Я бы не сказал, что это какое-то ожидаемое поведение от  программы.
Скорее надо сказать пользователю, что он неправильный путь к файлу указал

2020-06-02 15:59 UTC, SpirinEgor approved these changes

2020-11-27 11:53 UTC, merged